import os

DEEPSEEK_APIKEY = os.getenv('DEEPSEEK_APIKEY', '')
GLM_APIKEY = os.getenv('GLM_APIKEY', '')

DEFAULT_MODEL_DEEPSEEK = 'deepseek-chat'
DEFAULT_MODEL_GLM = 'glm-5.1'

DEFAULT_TEMPERATURE = 1.0
DEFAULT_MAX_TOKENS = 2048
ENABLE_DEEP_THINKING = False